### ISSUE TITLE
Rust wrappers for GUdevEnumerator

### ISSUE THREAD

**Issue by Calrama** [hfiguiere/gudev-rs#1]
Querying via a GUdevEnumerator allows for finer control over which devices should be matched. The low level C API calls are present in gudev-sys, but there are no high level wrappers for it.
Please consider adding them, as that - afaict - should make this a complete wrapper for gudev (and gudev's API seems unlikely to change anytime soon).

**Comment by hfiguiere** [comment]
I was rejoicing of having to review a pull request for this.

**Comment by Calrama** [comment]
Sure, [here you go](https://github.com/hfiguiere/gudev-rs/pull/2). If it looks good, you might want to release a new version.

**Comment by hfiguiere** [comment]
Thanks you so much.
